### ISSUE TITLE
Able to set store not to use?

### ISSUE THREAD

**Issue by apenny1313** [infopowerbroker/EpicMall#2]
Hi - is there a way to put a specific store or character to NOT buy from? I was asked to not buy from someone specific. 
apenny

**Comment by infopowerbroker** [comment]
The script is pretty dumb, just using this mafia function: https://wiki.kolmafia.us/index.php/Buy 

Easiest way for this to be solved is one of the two options:

What you can do: Remove the item from your list of things to buy (not ideal)
What they can do: "ignore" you and set the shop to not sell to folks on the ignore list. (probably best, especially if they are the ones that want you to stop buying stuff, unless you interact with them often in chat)

Mafia does not appear to make the distinction about which store to use, just lowest price, I can't think of anything else that can be done for this specific case.
